name: Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./banking-system-backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/banking-system-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./banking-system-frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/banking-system-frontend:latest

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/banking-system-backend:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/banking-system-frontend:latest
            sudo docker compose down
            sudo docker compose up -d --remove-orphans